import "../globals.css";
import Navbar from "../component/navbar";
import Sidebar from "../component/sidebar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function SubLayout({ children }) {
  return (
    <div className=" bg-grey100">
        <Navbar/>
        <div className="flex w-full min-h-screen ">
          <Sidebar/>
          {children}
        </div>
    </div> 
  );
}
