import "./globals.css";
import { AuthProvider } from "@/contexts/authcontext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className='bg-grey100 font-inter'>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
