import "./globals.css";
import Navbar from "./component/navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-grey100 font-inter'>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
